repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.5.2
    hooks:
      - id: commitizen-branch
        args:
          - --rev-range
          - main..HEAD
        stages:
          - push
  - repo: local
    hooks:
      - id: formatting
        name: formatting check
        description: runs cargo formatter to check that files are meeting its recommendations
        language: system
        types: 
          - rust
        entry: cargo fmt
        args:
          - --check
        always_run: true
        fail_fast: true
        pass_filenames: false
      - id: linting
        name: linting check
        description: runs cargo clippy to check that files are meeting its recommendations
        language: system
        types: 
          - rust
        entry: cargo clippy
        args:
          - --
          - -D
          - warnings
        always_run: true
        fail_fast: true
        pass_filenames: false
      - id: testing_unit
        name: running unit tests
        description: runs unit tests using builtin rust test runner
        language: system
        types: 
          - rust
        entry: cargo test
        always_run: true
        fail_fast: true
        pass_filenames: false
      - id: testing_bench
        name: running benchmark tests
        description: runs benchmark tests using Criterion (won't cause push to fail if regression found)
        language: system
        types: 
          - rust
        entry: cargo bench
        always_run: true
        fail_fast: true
        pass_filenames: false
default_install_hook_types:
  - pre-push
