[package]
name = "image_visual_comparator"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
lab = "0.11.0"

[dev-dependencies]
assert_fs = "1.0.13"
